apiVersion: v1
kind: Service
metadata:
  name: argo-node-web-app-service
  namespace: argo-node-web-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-web-app