apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-node-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-node-web
  template:
    metadata:
      labels:
        app: argo-node-web
    spec:
      containers:
      - image: mkowe/vue-weather-app:prod
        name: argo-node-web
        ports:
        - containerPort: 80
