apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-node-web-app
  name: argo-node-web-app
  namespace: argo-node-web-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-node-web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app:argo-node-web-app
    spec:
      containers:
      - image: mkowe/vue-weather-app:prod 
        name: argo-node-web-app
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3